# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/roc/Documents/FactoryTest

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/roc/Documents/FactoryTest

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roc/Documents/FactoryTest/CMakeFiles /home/roc/Documents/FactoryTest/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roc/Documents/FactoryTest/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named factory_test_server

# Build rule for target.
factory_test_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 factory_test_server
.PHONY : factory_test_server

# fast build rule for target.
factory_test_server/fast:
	$(MAKE) -f CMakeFiles/factory_test_server.dir/build.make CMakeFiles/factory_test_server.dir/build
.PHONY : factory_test_server/fast

can_test.o: can_test.c.o

.PHONY : can_test.o

# target to build an object file
can_test.c.o:
	$(MAKE) -f CMakeFiles/factory_test_server.dir/build.make CMakeFiles/factory_test_server.dir/can_test.c.o
.PHONY : can_test.c.o

can_test.i: can_test.c.i

.PHONY : can_test.i

# target to preprocess a source file
can_test.c.i:
	$(MAKE) -f CMakeFiles/factory_test_server.dir/build.make CMakeFiles/factory_test_server.dir/can_test.c.i
.PHONY : can_test.c.i

can_test.s: can_test.c.s

.PHONY : can_test.s

# target to generate assembly for a file
can_test.c.s:
	$(MAKE) -f CMakeFiles/factory_test_server.dir/build.make CMakeFiles/factory_test_server.dir/can_test.c.s
.PHONY : can_test.c.s

data.o: data.c.o

.PHONY : data.o

# target to build an object file
data.c.o:
	$(MAKE) -f CMakeFiles/factory_test_server.dir/build.make CMakeFiles/factory_test_server.dir/data.c.o
.PHONY : data.c.o

data.i: data.c.i

.PHONY : data.i

# target to preprocess a source file
data.c.i:
	$(MAKE) -f CMakeFiles/factory_test_server.dir/build.make CMakeFiles/factory_test_server.dir/data.c.i
.PHONY : data.c.i

data.s: data.c.s

.PHONY : data.s

# target to generate assembly for a file
data.c.s:
	$(MAKE) -f CMakeFiles/factory_test_server.dir/build.make CMakeFiles/factory_test_server.dir/data.c.s
.PHONY : data.c.s

factory_test_function.o: factory_test_function.c.o

.PHONY : factory_test_function.o

# target to build an object file
factory_test_function.c.o:
	$(MAKE) -f CMakeFiles/factory_test_server.dir/build.make CMakeFiles/factory_test_server.dir/factory_test_function.c.o
.PHONY : factory_test_function.c.o

factory_test_function.i: factory_test_function.c.i

.PHONY : factory_test_function.i

# target to preprocess a source file
factory_test_function.c.i:
	$(MAKE) -f CMakeFiles/factory_test_server.dir/build.make CMakeFiles/factory_test_server.dir/factory_test_function.c.i
.PHONY : factory_test_function.c.i

factory_test_function.s: factory_test_function.c.s

.PHONY : factory_test_function.s

# target to generate assembly for a file
factory_test_function.c.s:
	$(MAKE) -f CMakeFiles/factory_test_server.dir/build.make CMakeFiles/factory_test_server.dir/factory_test_function.c.s
.PHONY : factory_test_function.c.s

factory_test_server.o: factory_test_server.c.o

.PHONY : factory_test_server.o

# target to build an object file
factory_test_server.c.o:
	$(MAKE) -f CMakeFiles/factory_test_server.dir/build.make CMakeFiles/factory_test_server.dir/factory_test_server.c.o
.PHONY : factory_test_server.c.o

factory_test_server.i: factory_test_server.c.i

.PHONY : factory_test_server.i

# target to preprocess a source file
factory_test_server.c.i:
	$(MAKE) -f CMakeFiles/factory_test_server.dir/build.make CMakeFiles/factory_test_server.dir/factory_test_server.c.i
.PHONY : factory_test_server.c.i

factory_test_server.s: factory_test_server.c.s

.PHONY : factory_test_server.s

# target to generate assembly for a file
factory_test_server.c.s:
	$(MAKE) -f CMakeFiles/factory_test_server.dir/build.make CMakeFiles/factory_test_server.dir/factory_test_server.c.s
.PHONY : factory_test_server.c.s

serial_test.o: serial_test.c.o

.PHONY : serial_test.o

# target to build an object file
serial_test.c.o:
	$(MAKE) -f CMakeFiles/factory_test_server.dir/build.make CMakeFiles/factory_test_server.dir/serial_test.c.o
.PHONY : serial_test.c.o

serial_test.i: serial_test.c.i

.PHONY : serial_test.i

# target to preprocess a source file
serial_test.c.i:
	$(MAKE) -f CMakeFiles/factory_test_server.dir/build.make CMakeFiles/factory_test_server.dir/serial_test.c.i
.PHONY : serial_test.c.i

serial_test.s: serial_test.c.s

.PHONY : serial_test.s

# target to generate assembly for a file
serial_test.c.s:
	$(MAKE) -f CMakeFiles/factory_test_server.dir/build.make CMakeFiles/factory_test_server.dir/serial_test.c.s
.PHONY : serial_test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... factory_test_server"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... can_test.o"
	@echo "... can_test.i"
	@echo "... can_test.s"
	@echo "... data.o"
	@echo "... data.i"
	@echo "... data.s"
	@echo "... factory_test_function.o"
	@echo "... factory_test_function.i"
	@echo "... factory_test_function.s"
	@echo "... factory_test_server.o"
	@echo "... factory_test_server.i"
	@echo "... factory_test_server.s"
	@echo "... serial_test.o"
	@echo "... serial_test.i"
	@echo "... serial_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

